#!/usr/bin/env python
"""
    multishear-run coadd_id merun
"""

import sys
from sys import stdout,stderr
import deswl

from optparse import OptionParser
parser = OptionParser(__doc__)

parser.add_option("--nodots", action='store_true', default=False,
 help="Don't print progress dots.")
parser.add_option("--debug", default=0,
    help="Debug verbosity level. 0:none 1:dbg 2:xdbg. Default %default")

options, args = parser.parse_args(sys.argv[1:])

if len(args) < 2:
    parser.print_help()
    sys.exit(45)

coadd_id=int(args[0])
merun=args[1]

cp=deswl.wlpipe.CoaddProcessor(coadd_id, merun, 
                               nodots=options.nodots, debug=options.debug)
