# vim: set filetype=python :

import os
Import('env')

pyfile=env.File('wl-run.py')
install_subdir = 'bin'
targets = [pyfile]

if 'install' in COMMAND_LINE_TARGETS:
    RunInstall = env['_InstallProgram']
    RunInstall(env, targets, install_subdir)

if 'uninstall' in COMMAND_LINE_TARGETS:
    RunUninstall = env['_UninstallProgram']
    RunUninstall(env, targets, install_subdir)


